### ISSUE TITLE
Random SSL issue - at net.lightbody.bmp.proxy.jetty.util.LineInput.fill(LineInput.java:417) 

### ISSUE THREAD

**Issue by tkohegyi** [tkohegyi/mitmProxy#10]
This issue happens randomly, same code can run and fail later...
```
20:43:58.518 [SocketListener90-1] DEBUG n.l.b.p.jetty.http.HttpConnection - Normal handling issue
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:324) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:351) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:802) ~[na:na]
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:937) ~[na:na]
	at net.lightbody.bmp.proxy.jetty.util.LineInput.fill(LineInput.java:417) ~[main/:na]
	at net.lightbody.bmp.proxy.jetty.util.LineInput.fillLine(LineInput.java:482) ~[main/:na]
	at net.lightbody.bmp.proxy.jetty.util.LineInput.readLineBuffer(LineInput.java:273) ~[main/:na]
	at net.lightbody.bmp.proxy.jetty.util.LineInput.readLineBuffer(LineInput.java:259) ~[main/:na]
	at net.lightbody.bmp.proxy.jetty.http.HttpRequest.readHeader(HttpRequest.java:226) ~[main/:na]
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.readRequest(HttpConnection.java:764) ~[main/:na]
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.handleNext(HttpConnection.java:803) ~[main/:na]
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.handle(HttpConnection.java:744) ~[main/:na]
	at net.lightbody.bmp.proxy.jetty.http.SocketListener.handleConnection(SocketListener.java:183) ~[main/:na]
	at net.lightbody.bmp.proxy.jetty.util.ThreadedServer.handle(ThreadedServer.java:243) ~[main/:na]
	at net.lightbody.bmp.proxy.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:365) ~[main/:na]
```

**Comment by tkohegyi** [comment]
Closing here, follow this issue up at https://github.com/website-magyar/mitmJavaProxy/issues/2

**Comment by tkohegyi** [comment]
cannot reproduce for a while, so closing
