### ISSUE TITLE
Random SSL issue - SSLHandshakeException: Insufficient buffer remaining for AEAD cipher fragment (2).

### ISSUE THREAD

**Issue by tkohegyi** [tkohegyi/mitmProxy#12]
There is another SSL issue - in Java implementation:
```
javax.net.ssl.SSLHandshakeException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:133)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1408)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1314)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.upgrade(DefaultHttpClientConnectionOperator.java:191)
        at org.apache.http.impl.conn.BasicHttpClientConnectionManager.upgrade(BasicHttpClientConnectionManager.java:325)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:428)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
        at website.magyar.mitm.proxy.help.AbstractComplexProxyTool.httpGetWithApacheClient(AbstractComplexProxyTool.java:209)
        at website.magyar.mitm.proxy.MitmComplexProxyWithExternalServerTest.testSimpleRemoteGetRequestOverHTTPSThroughProxy(MitmComplexProxyWithExternalServerTest.java:79)

        Caused by:
        javax.crypto.BadPaddingException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)
            at java.base/sun.security.ssl.SSLCipher$T13GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1868)
            at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:260)
            at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
            at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
```

**Comment by tkohegyi** [comment]
This is a know issue, mentioned for example here: https://github.com/opendistro-for-elasticsearch/security/issues/70 
and the root problem is here: https://bugs.openjdk.java.net/browse/JDK-8221218 

Unfortunately we have nothing to do here, it is a bug in OpenJDK.

**Comment by stardustman** [comment]
bravo

**Comment by tkohegyi** [comment]
Note: Seems fixed - at least I cannot detect it since using the latest libs and Java 15.

**Comment by dineshnaik** [comment]
@tkohegyi How did you fix this ? I am also getting this error in few of my ES nodes where opendistro is installed for security. 
Also link https://github.com/opendistro-for-elasticsearch/security/issues/70 is not accessible .

**Comment by tkohegyi** [comment]
@dineshnaik I use JDK15 and later + org.bouncycastle/bcpkix-jdk18on/1.71.1 and I cannot repro it anymore 
in case you can, I would appreciate for a sample code / test case

**Comment by dss010101** [comment]
is this still an issue? im getting this error if security is enabled with the latest opensearch image

**Comment by tkohegyi** [comment]
@dss010101 I use OpenJDK15 and later + org.bouncycastle/bcpkix-jdk18on/1.72 lib 
in addition I use these additional java flags: -Djdk.tls.namedGroups="secp256r1, secp384r1, ffdhe2048, ffdhe3072"
so I cannot reproduce this issue anymore - in case you can, I would appreciate giving me a sample code / test case

Also - you said you are getting this issue - do you get this issue by using mitmJavaProxy (pls specify version) or just getting this issue by using java in general?

**Comment by dss010101** [comment]
> @dss010101 I use OpenJDK15 and later + org.bouncycastle/bcpkix-jdk18on/1.72 lib in addition I use these additional java flags: -Djdk.tls.namedGroups="secp256r1, secp384r1, ffdhe2048, ffdhe3072" so I cannot reproduce this issue anymore - in case you can, I would appreciate giving me a sample code / test case
> 
> Also - you said you are getting this issue - do you get this issue by using mitmJavaProxy (pls specify version) or just getting this issue by using java in general?

My issue isn't related to your project....google sent me here.  im basically trying to run this sample, and when i set 'tls on' in the fluentbit.conf, i see the same error.  

https://github.com/opensearch-project/data-prepper/tree/main/examples/log-ingestion

**Comment by tkohegyi** [comment]
Hi @dss010101 - what I see there that at https://github.com/opensearch-project/security/blob/main/build.gradle they use the mentioned library: implementation "org.bouncycastle:bcprov-jdk15on:${versions.bouncycastle}" - but was unable to figure out the used lib version - if it is less than 1.71.1 then that could be the problem.

**Comment by dss010101** [comment]
thank you, while i've moved on from open-search out of frustration - i'll pass this infomration on to the community as it may be helpful to others having the issue
