### ISSUE TITLE
Doesn't it support https?

### ISSUE THREAD

**Issue by workcheng** [tkohegyi/mitmProxy#24]
[SocketListener0-3] ERROR net.lightbody.bmp.proxy.selenium.KeyStoreManager - Fatal error creating/storing keystore or signing cert.
[SocketListener0-3] WARN net.lightbody.bmp.proxy.jetty.http.HttpConnection - CONNECT www.bing.com:443 HTTP/1.1
java.lang.Error: java.lang.RuntimeException: Ups, tried to create a Cert
	at net.lightbody.bmp.proxy.selenium.KeyStoreManager.<init>(KeyStoreManager.java:162)
	at net.lightbody.bmp.proxy.selenium.SeleniumProxyHandler.wireUpSslWithCyberVilliansCA(SeleniumProxyHandler.java:573)
	at net.lightbody.bmp.proxy.BrowserMobProxyHandler.wireUpSslWithCyberVilliansCA(BrowserMobProxyHandler.java:147)
	at net.lightbody.bmp.proxy.selenium.SeleniumProxyHandler.getSslRelayOrCreateNew(SeleniumProxyHandler.java:512)
	at net.lightbody.bmp.proxy.BrowserMobProxyHandler.getSslRelayOrCreateNew(BrowserMobProxyHandler.java:152)
	at net.lightbody.bmp.proxy.selenium.SeleniumProxyHandler.handleConnect(SeleniumProxyHandler.java:459)
	at net.lightbody.bmp.proxy.BrowserMobProxyHandler.handleConnect(BrowserMobProxyHandler.java:131)
	at net.lightbody.bmp.proxy.selenium.SeleniumProxyHandler.handle(SeleniumProxyHandler.java:149)
	at net.lightbody.bmp.proxy.jetty.http.HttpContext.handle(HttpContext.java:1345)
	at net.lightbody.bmp.proxy.jetty.http.HttpContext.handle(HttpContext.java:1309)
	at net.lightbody.bmp.proxy.jetty.http.HttpServer.service(HttpServer.java:830)
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.service(HttpConnection.java:730)
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.handleNext(HttpConnection.java:877)
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.handle(HttpConnection.java:742)
	at net.lightbody.bmp.proxy.jetty.http.SocketListener.handleConnection(SocketListener.java:183)
	at net.lightbody.bmp.proxy.jetty.util.ThreadedServer.handle(ThreadedServer.java:243)
	at net.lightbody.bmp.proxy.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:365)
Caused by: java.lang.RuntimeException: Ups, tried to create a Cert
	at net.lightbody.bmp.proxy.selenium.KeyStoreManager.createKeystore(KeyStoreManager.java:231)
	at net.lightbody.bmp.proxy.selenium.KeyStoreManager.<init>(KeyStoreManager.java:160)
	... 16 more
[SocketListener0-0] ERROR net.lightbody.bmp.proxy.selenium.KeyStoreManager - Fatal error creating/storing keystore or signing cert.
[SocketListener0-0] WARN net.lightbody.bmp.proxy.jetty.http.HttpConnection - CONNECT edge.microsoft.com:443 HTTP/1.1
java.lang.Error: java.lang.RuntimeException: Ups, tried to create a Cert
	at net.lightbody.bmp.proxy.selenium.KeyStoreManager.<init>(KeyStoreManager.java:162)
	at net.lightbody.bmp.proxy.selenium.SeleniumProxyHandler.wireUpSslWithCyberVilliansCA(SeleniumProxyHandler.java:573)
	at net.lightbody.bmp.proxy.BrowserMobProxyHandler.wireUpSslWithCyberVilliansCA(BrowserMobProxyHandler.java:147)
	at net.lightbody.bmp.proxy.selenium.SeleniumProxyHandler.getSslRelayOrCreateNew(SeleniumProxyHandler.java:512)
	at net.lightbody.bmp.proxy.BrowserMobProxyHandler.getSslRelayOrCreateNew(BrowserMobProxyHandler.java:152)
	at net.lightbody.bmp.proxy.selenium.SeleniumProxyHandler.handleConnect(SeleniumProxyHandler.java:459)
	at net.lightbody.bmp.proxy.BrowserMobProxyHandler.handleConnect(BrowserMobProxyHandler.java:131)
	at net.lightbody.bmp.proxy.selenium.SeleniumProxyHandler.handle(SeleniumProxyHandler.java:149)
	at net.lightbody.bmp.proxy.jetty.http.HttpContext.handle(HttpContext.java:1345)
	at net.lightbody.bmp.proxy.jetty.http.HttpContext.handle(HttpContext.java:1309)
	at net.lightbody.bmp.proxy.jetty.http.HttpServer.service(HttpServer.java:830)
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.service(HttpConnection.java:730)
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.handleNext(HttpConnection.java:877)
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.handle(HttpConnection.java:742)
	at net.lightbody.bmp.proxy.jetty.http.SocketListener.handleConnection(SocketListener.java:183)
	at net.lightbody.bmp.proxy.jetty.util.ThreadedServer.handle(ThreadedServer.java:243)
	at net.lightbody.bmp.proxy.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:365)
Caused by: java.lang.RuntimeException: Ups, tried to create a Cert
	at net.lightbody.bmp.proxy.selenium.KeyStoreManager.createKeystore(KeyStoreManager.java:231)
	at net.lightbody.bmp.proxy.selenium.KeyStoreManager.<init>(KeyStoreManager.java:160)
	... 16 more
[SocketListener0-0] ERROR net.lightbody.bmp.proxy.selenium.KeyStoreManager - Fatal error creating/storing keystore or signing cert.
[SocketListener0-0] WARN net.lightbody.bmp.proxy.jetty.http.HttpConnection - CONNECT edge.microsoft.com:443 HTTP/1.1

**Comment by suraj-mathew** [comment]
I was able to verify https using this project now (Dec 2024). Below is what I did. See if this solves your problem.

_NOTE: no root user or sudo permissions used anywhere in below steps_

- clone this repository master branch to the local machine
- compile and generate the jar file using the command `gradlew clean build -x test`  (_the `-x test` is to avoid the test execution after build_)
- once the build is success, the generated jar file will be available at \<repository folder\>/build/libs. There will be 4 jar files available. I took the one ending with `-all.jar`
-  Now, I created a new Java class file as mentioned in [their wiki](https://github.com/tkohegyi/mitmJavaProxy/wiki/2.-How-to-start-and-stop-the-proxy) to invoke the server start and specified the above obtained `mitm-java-proxy-....-all.jar` in the classpath
- Compiled and ran above new Java class by specifying the `-all.jar` in classpath and this argument `-Djdk.tls.namedGroups="secp256r1, secp384r1, ffdhe2048, ffdhe3072"`. The log will show the port number in which the proxy server is listening
- Opened browser (Mozilla Firefox for me) and went to Settings -> certificates -> view certificates -> authorities tab -> import button. Now, select the `.cer` certificate available in \<repository folder\>/src/main/resources/sslSupport folder.
- Open the browser's proxy settings -> manual proxy and give the proxy server machine's IP and port displayed from earlier step.
- Now, try accessing an https website from browser. It will get logged in the proxy program's log folder as well as the request resolves to the intended website.
- From curl too, we can verify the same via `curl curl --cacert <ABSOLUTE LOCATION OF THE .cer FILE> -x "http://PROXY SERVER IP: PORT" YOUR_INTENDED_HTTPS_WEBSITE_URL`

Warning: From the certificate already available in the repository, its validity ends by 30-Dec-2024 (Seen this from browser)
![image](https://github.com/user-attachments/assets/e8ccc052-ce17-489a-a0a3-a053e246ed58)

**Comment by tkohegyi** [comment]
Hi, @suraj-mathew - thank you for your comment, hoping that it helps @workcheng. No need to rebuild however, the release jar can be used, using the -Djava.tls.namedgroups is the key solution.
Please note that the latest cer is in the release jar, inside sslSupport folder, and the cer file is valid till ~2032.

Dear @workcheng - yes, it supports https, but the proxy need to be started/used with special https related settings, and the client need to be ready to allow the usage of this proxy. 

Please read the last paragraph of the [Readme](https://github.com/tkohegyi/mitmJavaProxy/blob/master/README.md), with title [SSL Support](https://github.com/tkohegyi/mitmJavaProxy/blob/master/README.md#ssl-support). Not sure what is the purpose of your usage scenario, this proxy usually in use between services, not really behind a browser, which is a kind of suspicious use - some browser explicitly denies the use of MITM proxy in case of HTTPS - as that is a huge security risk.
