### ISSUE TITLE
Random SSL issue - An established connection was aborted

### ISSUE THREAD

**Issue by tkohegyi** [tkohegyi/mitmProxy#9]
It is not determined when and why, but sometimes SSLException happens when proxying a request on HTTPS channel:

```
javax.net.ssl.SSLException: An established connection was aborted by the software in your host machine
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:137)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1460)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1368)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:437)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.upgrade(DefaultHttpClientConnectionOperator.java:191)
        at org.apache.http.impl.conn.BasicHttpClientConnectionManager.upgrade(BasicHttpClientConnectionManager.java:325)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:428)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
        at org.rockhill.mitm.proxy.help.AbstractComplexProxyTool.httpGetWithApacheClient(AbstractComplexProxyTool.java:205)
        at org.rockhill.mitm.proxy.MitmComplexProxyWithExternalServerTest.testSimpleLocalGetRequestOverHTTPSThroughProxy(MitmComplexProxyWithExternalServerTest.java:42)

        Caused by:
        java.net.SocketException: An established connection was aborted by the software in your host machine
            at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:326)
            at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:351)
            at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:802)
            at java.base/java.net.Socket$SocketInputStream.read(Socket.java:937)
            at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:450)
            at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165)
            at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
            ... 15 more
```

Would be nice to figure out why.

**Comment by tkohegyi** [comment]
Closing here, follow this up at https://github.com/website-magyar/mitmJavaProxy/issues/3

**Comment by tkohegyi** [comment]
cannot reproduce for a while, so closing
